// Code generated by protoc-gen-go. DO NOT EDIT.
// source: day.proto

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	day.proto

It has these top-level messages:
	Video
	Day
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Video struct {
	Title string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Rank  int32  `protobuf:"varint,2,opt,name=rank" json:"rank,omitempty"`
	Views int32  `protobuf:"varint,3,opt,name=views" json:"views,omitempty"`
	Kudos int32  `protobuf:"varint,4,opt,name=kudos" json:"kudos,omitempty"`
	Url   string `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	Thumb string `protobuf:"bytes,6,opt,name=thumb" json:"thumb,omitempty"`
}

func (m *Video) Reset()                    { *m = Video{} }
func (m *Video) String() string            { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()               {}
func (*Video) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Video) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Video) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Video) GetViews() int32 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Video) GetKudos() int32 {
	if m != nil {
		return m.Kudos
	}
	return 0
}

func (m *Video) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Video) GetThumb() string {
	if m != nil {
		return m.Thumb
	}
	return ""
}

type Day struct {
	Date   string   `protobuf:"bytes,1,opt,name=date" json:"date,omitempty"`
	Videos []*Video `protobuf:"bytes,2,rep,name=videos" json:"videos,omitempty"`
}

func (m *Day) Reset()                    { *m = Day{} }
func (m *Day) String() string            { return proto.CompactTextString(m) }
func (*Day) ProtoMessage()               {}
func (*Day) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Day) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Day) GetVideos() []*Video {
	if m != nil {
		return m.Videos
	}
	return nil
}

func init() {
	proto.RegisterType((*Video)(nil), "types.Video")
	proto.RegisterType((*Day)(nil), "types.Day")
}

func init() { proto.RegisterFile("day.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x49, 0xac, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x56, 0x6a, 0x65, 0xe4,
	0x62, 0x0d, 0xcb, 0x4c, 0x49, 0xcd, 0x17, 0x12, 0xe1, 0x62, 0x2d, 0xc9, 0x2c, 0xc9, 0x49, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x84, 0xb8, 0x58, 0x8a, 0x12, 0xf3, 0xb2,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x90, 0xca, 0xb2, 0xcc, 0xd4, 0xf2, 0x62,
	0x09, 0x66, 0xb0, 0x20, 0x84, 0x03, 0x12, 0xcd, 0x2e, 0x4d, 0xc9, 0x2f, 0x96, 0x60, 0x81, 0x88,
	0x82, 0x39, 0x42, 0x02, 0x5c, 0xcc, 0xa5, 0x45, 0x39, 0x12, 0xac, 0x60, 0x33, 0x41, 0x4c, 0xb0,
	0x3d, 0x19, 0xa5, 0xb9, 0x49, 0x12, 0x6c, 0x50, 0x7b, 0x40, 0x1c, 0x25, 0x7b, 0x2e, 0x66, 0x97,
	0xc4, 0x4a, 0x90, 0x75, 0x29, 0x89, 0x25, 0x30, 0x37, 0x80, 0xd9, 0x42, 0x2a, 0x5c, 0x6c, 0x65,
	0x20, 0x17, 0x16, 0x4b, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0xf1, 0xe8, 0x81, 0x9d, 0xae, 0x07,
	0x76, 0x76, 0x10, 0x54, 0x2e, 0x89, 0x0d, 0xec, 0x2d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xae, 0x9b, 0x95, 0x33, 0xe3, 0x00, 0x00, 0x00,
}
